# Generated by Django 4.2.30 on 2026-09-10 19:27

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_experiencia_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=150)),
                ('fecha_obtencion', models.DateField()),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-fecha_obtencion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='CVDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Curriculum Vitae - Desarrollo', max_length=100)),
                ('archivo', models.FileField(upload_to='cvs/dev/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='CVUXUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Curriculum Vitae - UX/UI', max_length=100)),
                ('archivo', models.FileField(upload_to='cvs/uxui/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si es formación en curso', null=True)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-fecha_inicio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.PositiveIntegerField(help_text='Nivel de habilidad del 1 al 100')),
                ('categoria', models.CharField(choices=[('Desarrollo', 'Desarrollo'), ('Diseño', 'Diseño'), ('Otros', 'Otros')], max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
