# Generated by Django 4.2.30 on 2026-09-11 00:57

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certificacion_cvdev_cvuxui_formacion_habilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='url_repo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='url_sitio',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='contenido_html',
            field=django_ckeditor_5.fields.CKEditor5Field(default=' ', verbose_name='Contenido Detallado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_corta',
            field=models.TextField(default=' ', help_text='Para la card del Home', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='core.habilidad'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='icono_lucide',
            field=models.CharField(default='folder', help_text="Nombre del icono de Lucide (ejemplo: 'folder', 'code', 'user', etc.)", max_length=50),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
