# Generated by Django 4.2.30 on 2026-09-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_proyecto_descripcion_remove_proyecto_url_repo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='contenido_html',
            field=models.TextField(verbose_name='Contenido Detallado HTML'),
        ),
    ]
