"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Revisamos si estamos en el servidor de producción o en tu computador
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'local')

# ==========================================
# SEGURIDAD Y ENTORNO
# ==========================================
# Si estamos en producción lee la llave secreta del servidor, si no, usa la local
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-7ve3h+rq+ptn&%zr(1%!bz$4=qf1!22nv0hg0#rxk&#yd1wap*')

# Solo será True si NO estamos en producción
DEBUG = ENVIRONMENT != 'production'

# Permite que el sitio cargue en tu dominio y en el servidor cloud
ALLOWED_HOSTS = ['aldoaldoaldo.com', 'www.aldoaldoaldo.com', 'localhost', '127.0.0.1', '.onrender.com', '.up.railway.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==========================================
# ARCHIVOS ESTÁTICOS Y MEDIA
# ==========================================
STATIC_URL = 'static/'
# Esto le dice al servidor dónde agrupar todos los estáticos para producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'undo', 'redo'],
    }
}

# ==========================================
# CONFIGURACIÓN DE CORREOS
# ==========================================
if ENVIRONMENT == 'production':
    # CONFIGURACIÓN REAL (SE ACTIVA EN LA NUBE)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.ionos.com' # O el servidor SMTP que decidas usar
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get('EMAIL_USER') 
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')
    DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_USER')
else:
    # CONFIGURACIÓN DE PRUEBA (EN TU COMPUTADOR)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'prueba@localhost.com'
